sudo: required

services:
  - docker

env:
  COMPOSE_VERSION: 1.24.1

before_install:
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - curl -sS https://getcomposer.org/installer | php
  - chmod +x ./composer.phar
  - ./composer.phar --version
  - ./composer.phar install -d web_calc
script:
  - docker-compose build
  - docker-compose up app_test

notifications:
  email:
    - cazal.kevin.a@gmail.com